### ISSUE TITLE
Automatic Server URL Discovery

### ISSUE THREAD

**Issue by ProbablePrime** [WatchBeam/beam-interactive-node2#34]
The client should retrieve a server instance from: https://beam.pro/api/v1/interactive/hosts and use that instead of requiring the developer to retrieve one.

I'd like to look for a lightweight HTTP library to include here as most are large and seem wasteful for just one HTTP request.

**Comment by kateract** [comment]
Is this different then [PR 36](https://github.com/WatchBeam/beam-interactive-node2/pull/36)?

**Comment by ProbablePrime** [comment]
#36 Resolves this, I didn't remember to include the fixes messages to automatically close this. Closing it now :)
